# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GomokuFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('files', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='filesdata',
            name='gomoku_files',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gomokufiles.GomokuFiles'),
        ),
    ]
