# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomokufiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesdata',
            name='gomoku_files',
        ),
        migrations.AddField(
            model_name='gomokufiles',
            name='game_data',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='FilesData',
        ),
    ]
