# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomokufiles', '0002_auto_20180415_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gomokufiles',
            name='name',
        ),
        migrations.AddField(
            model_name='gomokufiles',
            name='color_swap',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gomokufiles',
            name='game_record',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gomokufiles',
            name='player_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gomokufiles',
            name='player_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gomokufiles',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
