# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomokufiles', '0003_auto_20180418_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='gomokufiles',
            name='score',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
