# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomokufiles', '0004_gomokufiles_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gomokufiles',
            name='game_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
