# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('gomokufiles', '0005_gomokufiles_game_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GomokuUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gomoku_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gomokufiles.GomokuFiles')),
            ],
        ),
    ]
