# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomokufiles', '0006_gomokuuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='gomokuuser',
            name='email',
            field=models.EmailField(default='', max_length=64, unique=True),
        ),
    ]
