# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gomokufiles', '0007_gomokuuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gomokuuser',
            name='gomoku_files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gomokufiles.GomokuFiles'),
        ),
    ]
