# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomokufiles', '0008_auto_20180425_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gomokuuser',
            name='gomoku_files',
        ),
        migrations.AddField(
            model_name='gomokufiles',
            name='gomoku_user',
            field=models.ManyToManyField(null=True, to='gomokufiles.GomokuUser'),
        ),
    ]
