# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomoku_project', '0002_remove_game_game_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_record',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
