# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gomoku_project', '0003_game_game_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_record',
        ),
    ]
